### ISSUE TITLE
Error Execution

### ISSUE THREAD

**Issue by tXambe** [anshumanpattnaik/http-request-smuggling#5]
Hello,

when I run the script I have this error:

```

Traceback (most recent call last):
  File "/opt/HTTP-SMUGGLING/http-request-smuggling/smuggle.py", line 130, in <module>
    utils.print_header()
  File "/opt/HTTP-SMUGGLING/http-request-smuggling/lib/Utils.py", line 43, in print_header
    cprint(figlet_format(self.title.center(20), font='cybermedium'), 'red', attrs=['bold'])
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 65, in figlet_format
    fig = Figlet(font, **kwargs)
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 794, in __init__
    self.setFont()
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 801, in setFont
    self.Font = FigletFont(font=self.font)
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 126, in __init__
    self.data = self.preloadFont(font)
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 147, in preloadFont
    raise FontNotFound(font)
pyfiglet.FontNotFound: cybermedium

```

I have installed pyfiglet library 

A greeting and thanks

**Comment by anshumanpattnaik** [comment]
Hello @tXambe ,  
Did you install the packages using requirements.txt?

**Comment by tXambe** [comment]
Hello,

Yes 

A greeting and thanks

**Comment by anshumanpattnaik** [comment]
@tXambe, Did you install the packages using virtual environment because It's working fine for me.
